// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFcsbWvFcJtXV7YAvptYRMovPGoLR2MX4',
    appId: '1:791824155693:web:0622266e56fbf3cc8464a4',
    messagingSenderId: '791824155693',
    projectId: 'gyefo-clocks',
    authDomain: 'gyefo-clocks.firebaseapp.com',
    storageBucket: 'gyefo-clocks.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcNurTky1PKXEEnP_sv0BEFLgT6q7f10M',
    appId: '1:791824155693:android:3fa65d884bdb76008464a4',
    messagingSenderId: '791824155693',
    projectId: 'gyefo-clocks',
    storageBucket: 'gyefo-clocks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO-_sdacRFFL6LkefxlwmHkoCcb9aq1Dw',
    appId: '1:791824155693:ios:d720253d1bf7c8bb8464a4',
    messagingSenderId: '791824155693',
    projectId: 'gyefo-clocks',
    storageBucket: 'gyefo-clocks.firebasestorage.app',
    iosBundleId: 'com.example.gyefoClockingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO-_sdacRFFL6LkefxlwmHkoCcb9aq1Dw',
    appId: '1:791824155693:ios:d720253d1bf7c8bb8464a4',
    messagingSenderId: '791824155693',
    projectId: 'gyefo-clocks',
    storageBucket: 'gyefo-clocks.firebasestorage.app',
    iosBundleId: 'com.example.gyefoClockingApp',
  );
}
